on: [push, workflow_dispatch]

name: build

jobs:
  all:
    name: pixfetch
    strategy:
      matrix:
        target: [aarch64-linux-android, aarch64-unknown-linux-musl, arm-unknown-linux-musleabihf, i586-unknown-linux-musl, i686-unknown-linux-musl, mips-unknown-linux-musl, x86_64-unknown-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }}
